# Default values for profile-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: vldmr/profile-service

service:
  type: NodePort
  port: 8000
