apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      initContainers:
        - name: check-db-ready
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PORT
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $POSTGRES_HOST  -p  $POSTGRES_PORT; 
              do echo waiting for database; sleep 2; done;
      containers:
      - name: post-install-job
        envFrom:
          - configMapRef:
              name: postgres-config
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: POSTGRES_DB
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ printf "%s-%s" .Release.Name "postgresql" }}
                key: postgresql-postgres-password
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_SERVICE_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_USER
        image: postgres:latest
        command:
          - sh
          - "-c"
          - |
            PGPASSWORD=$POSTGRES_PASSWORD psql -d $POSTGRES_DB -U $POSTGRES_USER -h $POSTGRES_HOST -p $POSTGRES_PORT <<'EOF'
              CREATE EXTENSION pgcrypto;
              CREATE TABLE IF NOT EXISTS public.users (
                id SERIAL,
                email VARCHAR UNIQUE,
                password VARCHAR,
                phone VARCHAR,
                username VARCHAR
              );
              GRANT CONNECT ON DATABASE $(POSTGRES_DB) TO "$(POSTGRES_SERVICE_USER)";
              GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "$(POSTGRES_SERVICE_USER)";
              GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "$(POSTGRES_SERVICE_USER)";
            EOF

  backoffLimit: 0
