{
 "title": "Arch Homework Golden Signals",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "percentile", "label": "Percentile", "query": "0.5, 0.95, 0.99, 1" },
   { "name": "interval", "label": "Interval", "query": "1m, 5m, 15m, 30m" }
  ]
 },
 "panels": [
  {
   "title": "Postgres Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace='crud-ns', pod='test-postgresql-0'}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Postgres CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace='crud-ns', pod='test-postgresql-0'}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"crud-ns\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"crud-ns\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (method, path) (rate(http_request_duration_seconds_bucket[$interval]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, \n      sum by (le, path, method) \n         (rate(http_request_duration_seconds_bucket[$interval]))\n) * 1000",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"[4-5].+\"}[$interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}