---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: profile-service # Перезаписываем уже существующий ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-url: http://auth-auth-service.default.svc.cluster.local/check/
    nginx.ingress.kubernetes.io/auth-response-headers: x-auth-token
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: / # Направляем все запросы к echoserver
            pathType: Prefix
            backend:
              service:
                name: profile-profile-service
                port:
                  number: 8000