---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: profile
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: http://auth-auth-service.arch.svc.cluster.local:8000/check/
    nginx.ingress.kubernetes.io/auth-response-headers: x-auth-token
spec:
  rules:
    - http:
        paths:
          - path: / # Направляем все запросы к profile
            pathType: Prefix
            backend:
              service:
                name: profile-profile-service
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /auth(/|$)(.*) # Направляем все запросы /auth к auth-service. Создаем отдельный Ingress изза аннотаций rewrite
            pathType: Prefix
            backend:
              service:
                name: auth-auth-service
                port:
                  number: 8000