apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: crud-namespace
  labels:
    app: postgres
data:
  POSTGRES_DB: otusdb
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
