apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-service
  namespace: crud-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crud-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: crud-service
    spec:
      containers:
        - name: crud-service
          image: vldmr/simple-crud:1.0.2
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: dbuser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: dbpassword
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: crud-service
  namespace: crud-namespace
spec:
  type: NodePort
  selector:
    app: crud-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crud-ingress
  namespace: crud-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: crud-service
                port:
                  number: 8000
