apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-migration
  namespace: crud-namespace
  labels:
    app: postgres-migration
spec:
  template:
    metadata:
      name: postgres-migration
      labels:
        app: postgres-migration
    spec:
      restartPolicy: Never
      containers:
        - name: create-table
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: dbuser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret-config
                  key: dbpassword
          image: postgres:latest
          command:
            - sh
            - "-c"
            - |
              PGPASSWORD=$POSTGRES_PASSWORD psql -d $POSTGRES_DB -U $POSTGRES_USER -h $POSTGRES_HOST -p $POSTGRES_PORT <<'EOF'
              CREATE TABLE IF NOT EXISTS users (
                id SERIAL,
                email VARCHAR UNIQUE,
                phone VARCHAR,
                username VARCHAR
              );
              EOF
  backoffLimit: 0 #number of retries before considering a Job as failed
