apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: crud-namespace
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: crud-namespace
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: postgredb
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - name: postgredb
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgredb
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-migration
  namespace: crud-namespace
  labels:
    app: postgres-migration
spec:
  template:
    metadata:
      name: postgres-migration
      labels:
        app: postgres-migration
    spec:
      restartPolicy: Never
      containers:
        - name: create-table
          envFrom:
            - configMapRef:
                name: postgres-config
          env:
            - name: DATABASE_URI
              value: postgres
          image: postgres:latest
          command:
            - sh
            - "-c"
            - |
              PGPASSWORD=$POSTGRES_PASSWORD psql -d $POSTGRES_DB -U $POSTGRES_USER -h $DATABASE_URI  <<'EOF'
              CREATE TABLE IF NOT EXISTS users (
                id SERIAL,
                email VARCHAR UNIQUE,
                phone VARCHAR,
                username VARCHAR
              );
              EOF
  backoffLimit: 0 #number of retries before considering a Job as failed
